name: toolchain
description: Setup toolchain for development

inputs:
  dioxus-version:
    description: Version of dioxus used in the project
    required: true
    default: 0.7.3

runs:
  using: composite
  steps:
    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
        libwebkit2gtk-4.1-dev \
        build-essential \
        curl \
        file \
        libxdo-dev \
        libssl-dev \
        libayatana-appindicator3-dev \
        librsvg2-dev \
        libgtk2.0-dev

      shell: bash

    - name: Install dx
      run: |
        curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
        cargo binstall dioxus-cli@${{ inputs.dioxus-version }}
        rustup target add wasm32-unknown-unknown

      shell: bash

    - name: Cache Node modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: make dependencies

      shell: bash

    - name: Create .env file
      run: |
        cp .env.ci.dist .env

      shell: bash
